site_name: Luohe High School
site_url: http://lhgz.net
copyright: Copyright &copy; 2002 - 2021 漯河市高级中学
theme:
  name: material
  language: zh
  favicon: assets/favicon.png
  logo: assets/favicon.png
  palette:
    - scheme: default
      toggle: 
        icon: material/brightness-7
        name: Switch to dark mode
      primary: green
      accent: light green
    
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: green
      accent: light green
